# What program(s) have to be built
PROGRAMS = ex5_1

# Dependencies for the program(s) to build
ex5_1: ../common/remregs.o ../common/wperror.o ../common/robot.o ../common/utils.o ex5_1.o

# Includes the common Makefile with the various rules
include ../common/Makefile.inc